CC = g++
EXC = Exe.exe
FILE1 = FILE
AdminMundial:
	${CC} src/main.cpp src/Continente.cpp src/Pais.cpp src/PaisEnDesarrollo.cpp src/PaisPrimerMundo.cpp  src/Planeta.cpp src/Funciones.cpp -o ${EXC}
	./${EXC}
doxygen:
	firefox html/index.html