CC = g++
EXC = Exe.exe
FILE1 = FILE
Ejemplos:
	${CC} ${FILE1}.cpp -o ${EXC}
	./${EXC}

Headers:
	${CC} SeparandoArchivos/main.cpp SeparandoArchivos/persona.cpp -o ${EXC}
	./${EXC}

HeadersExcercise:
	${CC} SeparandoArchivosEjercicio/Student.cpp SeparandoArchivosEjercicio/main.cpp -o ${EXC}
	./${EXC}